steps:
- name: 'gcr.io/corrupt-mnist/training'
  args: ['build', '-t', 'gcr.io/mlops-test-project-410913/training', '.']
- name: 'gcr.io/corrupt-mnist/training'
  args: ['push', 'gcr.io/mlops-test-project-410913/training']
