steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - "--tag=gcr.io/mlops-test-project-410913/training"
  - "--file=./dockerfiles/train_model.dockerfile"
  - .
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops-test-project-410913/training']
